### PR TITLE
chore(root): add commit hooks & nvm

### PR DESCRIPTION
**Pull request by evenstensberg**
## Summary of the changes
Adds husky and nvm.

## Related issue
Ongoing improvements, no issue subject to closing yet.

### CODE REVIEW

**Review by GCHQ-Developer-530 — DISMISSED** [review]

**Review by GCHQ-Developer-299 — APPROVED** [review]

**Comment by GCHQ-Developer-299** [comment]
Approved, but there is conflict in the package-lock - once you've got that sorted we can merge :)

**Comment by evenstensberg** [comment]
PTAL

**Comment by GCHQ-Developer-299** [comment]
@evenstensberg  looks like something's up with the packages, failing the build

**Comment by evenstensberg** [comment]
Yes, I think that is solved in #28

**Pull request closed without merging**
